"""Integrate latest model changes

Revision ID: 1439a2148737
Revises: 
Create Date: 2025-09-25 13:43:08.889927

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1439a2148737'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Emergency_Event',
    sa.Column('eme_id', sa.Integer(), nullable=False),
    sa.Column('disaster_type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('eme_id')
    )
    op.create_table('Resource',
    sa.Column('res_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('res_id')
    )
    op.create_table('Task',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('Team',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('team_leader', sa.String(length=100), nullable=True),
    sa.Column('personnel', sa.Integer(), nullable=True),
    sa.Column('equipment', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Affected_Area',
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('damage_extent', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['Emergency_Event.eme_id'], ),
    sa.PrimaryKeyConstraint('area_id')
    )
    op.create_table('Event_Requires_Task',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['Emergency_Event.eme_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['Task.task_id'], ),
    sa.PrimaryKeyConstraint('event_id', 'task_id')
    )
    op.create_table('Task_DoneBy_Team',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['Task.task_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['Team.team_id'], ),
    sa.PrimaryKeyConstraint('task_id', 'team_id')
    )
    op.create_table('Team_Has_Resource',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('res_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['res_id'], ['Resource.res_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['Team.team_id'], ),
    sa.PrimaryKeyConstraint('team_id', 'res_id')
    )
    op.create_table('Affected_Individual',
    sa.Column('individual_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('injury_type', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['Affected_Area.area_id'], ),
    sa.PrimaryKeyConstraint('individual_id')
    )
    op.create_table('Donation',
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['Affected_Area.area_id'], ),
    sa.PrimaryKeyConstraint('donation_id')
    )
    op.create_table('Evacuation',
    sa.Column('eva_id', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('transport', sa.String(length=100), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['Affected_Area.area_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['Team.team_id'], ),
    sa.PrimaryKeyConstraint('eva_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_event',
    sa.Column('eme_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('disaster_type', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('eme_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('affected_individual',
    sa.Column('individual_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('injury_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('severity', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('area_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['affected_area.area_id'], name=op.f('affected_individual_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('individual_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('evacuation',
    sa.Column('eva_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('destination', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('transport', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('area_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('team_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['affected_area.area_id'], name=op.f('evacuation_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], name=op.f('evacuation_ibfk_2'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('eva_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('affected_area',
    sa.Column('area_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('population', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('damage_extent', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('event_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['emergency_event.eme_id'], name='affected_area_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('area_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('role', mysql.ENUM('admin', 'user'), server_default=sa.text("'user'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)

    op.create_table('donation',
    sa.Column('donation_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('amount', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('area_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['affected_area.area_id'], name=op.f('donation_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('donation_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('event_requires_task',
    sa.Column('event_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['emergency_event.eme_id'], name=op.f('event_requires_task_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], name=op.f('event_requires_task_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'task_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('task',
    sa.Column('task_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_name', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('task_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('team',
    sa.Column('team_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('team_leader', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('personnel', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('equipment', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('team_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('task_doneby_team',
    sa.Column('task_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], name=op.f('task_doneby_team_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], name=op.f('task_doneby_team_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'team_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('resource',
    sa.Column('res_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('res_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Evacuation')
    op.drop_table('Donation')
    op.drop_table('Affected_Individual')
    op.drop_table('Team_Has_Resource')
    op.drop_table('Task_DoneBy_Team')
    op.drop_table('Event_Requires_Task')
    op.drop_table('Affected_Area')
    op.drop_table('User')
    op.drop_table('Team')
    op.drop_table('Task')
    op.drop_table('Resource')
    op.drop_table('Emergency_Event')
    # ### end Alembic commands ###
